- name: Launch EC2 instance
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - vars.yml
  roles:
    - create_instance

- name: Wait for EC2 instance to appear in inventory
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Pause to allow EC2 registration
      pause:
        seconds: 60

- name: Configure EC2 (Frontend + Backend)
  hosts: tag_Environment_Dev
  become: true
  gather_facts: yes
  roles:
    - frontend
    - backend
