---
- name: Launch EC2 instance
  amazon.aws.ec2_instance:
        name: "{{ instance_name }}"
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ ami_id }}"
        region: "{{ region }}"
        wait: yes
        count: 1
        # vpc_subnet_id: "{{ subnet_id }}"
        security_group: "{{ security_group }}"
        network:
          assign_public_ip: true
        tags:
          Environment: Dev
        register: ec2

- name: Print Public IP
  debug:
    msg: "Public IP: {{ ec2.instances[0].public_ip_address }}"
       # msg: "Instance ID: {{ ec2.instances[0].instance_id }}"
