- name: Launch EC2 instance
  amazon.aws.ec2_instance:
    name: "{{ instance_name }}"
    key_name: "{{ key_name }}"
    instance_type: "{{ instance_type }}"
    image_id: "{{ ami_id }}"
    region: "{{ region }}"
    wait: true
    count: 1
    security_group: "{{ security_group }}"
    network:
      assign_public_ip: true
    tags:
      Environment: Dev
